### ISSUE TITLE
Missing build.log after successful petsc build on Mavericks

### ISSUE THREAD

**Issue by tweigand** [hashdist/hashstack#441]
Hi, I'm getting an ERROR due to a missing build.log file. I can watch the file with tail -f to see that the build is succeeding, but it seems to be getting wiped out after that, causing this error:

[petsc] Building petsc/cath2bykvzop, follow log with:
[petsc]   tail -f /Users/tim/.hashdist/tmp/petsc-cath2bykvzop/build.log
[ERROR] [Errno 2] No such file or directory: u'/Users/tim/.hashdist/tmp/petsc-cath2bykvzop/build.log'

I've tried this with the stable/cygwin branch and with master:

HASHDIST_VERSION : 66c8115e4ca98571f6d3697a1bf4769200a81e40
HASHSTACK_VERSION: a057ae0a5392cce0895d63597959b5b9fac7089a

and

HASHDIST_VERSION : 66c8115e4ca98571f6d3697a1bf4769200a81e40
HASHSTACK_VERSION: 284450b25bebd2b527b943261b45869a00ad85f9

**Comment by johannesring** [comment]
Someone hit this problem again: http://fenicsproject.org/pipermail/fenics-support/2015-February/001336.html

**Comment by certik** [comment]
We need to rename it to `_hashdist/build.log`.

**Comment by johannesring** [comment]
I have made a [pull request](https://github.com/hashdist/hashdist/pull/348) for hashdist that fixes this issue now.

**Comment by johannesring** [comment]
Fixed by [#348](https://github.com/hashdist/hashdist/pull/348) in hashdist.
