### ISSUE TITLE
Matplotlib is installed without working backend

### ISSUE THREAD

**Issue by mikaem** [hashdist/hashstack#606]
I just installed fenics using hashdist on a ubuntu 14.04. With it comes installations of a lot of packages (see https://bitbucket.org/fenics-project/fenics-developer-tools/src/803cb8b5fee62862916d4ef95e3119075d717011/install/profiles/fenics-deps.Linux.yaml?at=master), both python and matplotlib. My problem is that there is no working backend in matplotlib (the only shared object in site-packages/matplotlib/backends is _backend_agg.so). @johannesring suggested it was because there is no python-tk package installed and matplotlib should probably be installed with tk as dependency. I tried adding tk to build and run dependencies in the matplotlib.yaml file, bit no luck, still no more backends.

Any help appreciated

Mikael

**Comment by johannesring** [comment]
Maybe it is `python` that needs to be built with `tk`? Try adding it to the `build_with` option to `python`:

    packages:
      python:
        link: shared
        build_with: |
          tk

**Comment by mikaem** [comment]
That triggered a recompilation of just about everything, but it worked:-)

**Comment by certik** [comment]
Interesting, thanks @johannesring.

**Comment by ahmadia** [comment]
This is something that we currently manage at the profile level.  It's hard to figure out how to communicate package dependencies to each other.
