### ISSUE TITLE
VTK fails on Ubuntu

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#634]
This is the interesting part from the [build.log](https://gist.github.com/johannesring/09f33bf41f1cfe1ab97d).

    2015/02/16 17:08:47 - INFO: [package:run_job] [ 59%] Building CXX object Rendering/CMakeFiles/vtkRendering.dir/vtkGraphicsFactory.cxx.o
    2015/02/16 17:08:47 - INFO: [package:run_job] In file included from /home/martinal/.hashdist/tmp/vtk-6jaf25efaug6/Rendering/vtkGraphicsFactory.cxx:66:0:
    2015/02/16 17:08:47 - INFO: [package:run_job] /home/martinal/.hashdist/tmp/vtk-6jaf25efaug6/Rendering/vtkXRenderWindowInteractor.h:37:74: fatal error: X11/StringDefs.h: No such file or directory
    2015/02/16 17:08:47 - INFO: [package:run_job]  #include <X11/StringDefs.h> // Needed for X types in the public interface
    2015/02/16 17:08:47 - INFO: [package:run_job]                                                                           ^
    2015/02/16 17:08:47 - INFO: [package:run_job] compilation terminated.
    2015/02/16 17:08:47 - INFO: [package:run_job] [ 59%] Building CXX object IO/CMakeFiles/vtkIOPythonD.dir/vtkGaussianCubeReaderPython.cxx.o
    2015/02/16 17:08:48 - INFO: [package:run_job] [ 59%] Building CXX object Graphics/CMakeFiles/vtkGraphicsPythonD.dir/vtkEdgeSubdivisionCriterionPython.cxx.o
    2015/02/16 17:08:48 - INFO: [package:run_job] Rendering/CMakeFiles/vtkRendering.dir/build.make:1165: recipe for target 'Rendering/CMakeFiles/vtkRendering.dir/vtkGraphicsFactory.cxx.o' failed
    2015/02/16 17:08:48 - INFO: [package:run_job] make[2]: *** [Rendering/CMakeFiles/vtkRendering.dir/vtkGraphicsFactory.cxx.o] Error 1
    2015/02/16 17:08:48 - INFO: [package:run_job] CMakeFiles/Makefile2:2734: recipe for target 'Rendering/CMakeFiles/vtkRendering.dir/all' failed
    2015/02/16 17:08:48 - INFO: [package:run_job] make[1]: *** [Rendering/CMakeFiles/vtkRendering.dir/all] Error 2
    2015/02/16 17:08:48 - INFO: [package:run_job] make[1]: *** Waiting for unfinished jobs....

The file `X11/StringDefs.h` is available in the libxt-dev package. Is this assumed to be in place when building `vtk`?

**Comment by certik** [comment]
Yes, I think the X11 headers must be in place unfortunately.

**Comment by johannesring** [comment]
Ok, thanks for the reply!
