### ISSUE TITLE
Hashstack's gcc's rpath gets erased sometimes

### ISSUE THREAD

**Issue by certik** [hashdist/hashstack#649]
Now when #646 is in, there is still a problem that sometimes the original (correct) rpath provided by gcc gets overridden by either cmake or autotools. For example:
```
certik@redhawk:~/repos/hashstack/default$ ldd lib/libginac.so
lib/libginac.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by lib/libginac.so)
lib/libginac.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by lib/libginac.so)
	linux-vdso.so.1 =>  (0x00007fff6d3ff000)
	libcln.so.6 => /local/certik/bld/cln/ac7u7rpiqkr4/lib/libcln.so.6 (0x00007fc0350f1000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fc034dcf000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc034b4b000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc034935000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc0345a0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc035954000)
```
The libstdc++ is taken from the system. This happens with cmake as well:
```
certik@redhawk:~/repos/hashstack/default$ ldd lib/libamesos.so
lib/libamesos.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /local/certik/bld/trilinos/msytmpjzt4wr/lib/libepetraext.so.11)
lib/libamesos.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /local/certik/bld/trilinos/msytmpjzt4wr/lib/libteuchosnumerics.so.11)
lib/libamesos.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /local/certik/bld/trilinos/msytmpjzt4wr/lib/libteuchoscomm.so.11)
lib/libamesos.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /local/certik/bld/trilinos/msytmpjzt4wr/lib/libteuchosparameterlist.so.11)
lib/libamesos.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /local/certik/bld/trilinos/msytmpjzt4wr/lib/libteuchoscore.so.11)
lib/libamesos.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /local/certik/bld/trilinos/msytmpjzt4wr/lib/libtriutils.so.11)
	linux-vdso.so.1 =>  (0x00007fffe47ff000)
	libepetraext.so.11 => /local/certik/bld/trilinos/msytmpjzt4wr/lib/libepetraext.so.11 (0x00007f6f4fbbb000)
	libepetra.so.11 => /local/certik/bld/trilinos/msytmpjzt4wr/lib/libepetra.so.11 (0x00007f6f4f84d000)
	libteuchosremainder.so.11 => /local/certik/bld/trilinos/msytmpjzt4wr/lib/libteuchosremainder.so.11 (0x00007f6f4f647000)
	libteuchosnumerics.so.11 => /local/certik/bld/trilinos/msytmpjzt4wr/lib/libteuchosnumerics.so.11 (0x00007f6f4f422000)
	libteuchoscomm.so.11 => /local/certik/bld/trilinos/msytmpjzt4wr/lib/libteuchoscomm.so.11 (0x00007f6f4f146000)
	libteuchosparameterlist.so.11 => /local/certik/bld/trilinos/msytmpjzt4wr/lib/libteuchosparameterlist.so.11 (0x00007f6f4ebf8000)
	libteuchoscore.so.11 => /local/certik/bld/trilinos/msytmpjzt4wr/lib/libteuchoscore.so.11 (0x00007f6f4e9a0000)
	libtriutils.so.11 => /local/certik/bld/trilinos/msytmpjzt4wr/lib/libtriutils.so.11 (0x00007f6f4e74e000)
	libopenblas.so.0 => /local/certik/bld/openblas/2wc6yoy6i5m5/lib/libopenblas.so.0 (0x00007f6f4d87f000)
	libmpichcxx.so.10 => /local/certik/bld/mpi/s3onu7dmekim/lib/libmpichcxx.so.10 (0x00007f6f4d65c000)
	libmpich.so.10 => /local/certik/bld/mpi/s3onu7dmekim/lib/libmpich.so.10 (0x00007f6f4d1ea000)
	libopa.so.1 => /local/certik/bld/mpi/s3onu7dmekim/lib/libopa.so.1 (0x00007f6f4cfe9000)
	libmpl.so.1 => /local/certik/bld/mpi/s3onu7dmekim/lib/libmpl.so.1 (0x00007f6f4cde4000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f6f4cbc1000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6f4c9a4000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f6f4c69d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6f4c419000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f6f4c203000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6f4be6e000)
	libmpichf90.so.10 => /local/certik/bld/mpi/s3onu7dmekim/lib/libmpichf90.so.10 (0x00007f6f4bc6c000)
	libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f6f4b979000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6f501fc000)
	libquadmath.so.0 => not found
	libquadmath.so.0 => not found
	libquadmath.so.0 => /local/certik/bld/gcc/lveg4hd6gebz/lib/../lib64/libquadmath.so.0 (0x00007f6f4b73a000)
```
Some other libraries are ok:
```
certik@redhawk:~/repos/hashstack/default$ ldd lib/libblas.so
	linux-vdso.so.1 =>  (0x00007fff14894000)
	libgfortran.so.3 => /local/certik/bld/gcc/hc3bnbyc3hsf/lib/libgfortran.so.3 (0x00007f1270a95000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f12707f5000)
	libgcc_s.so.1 => /local/certik/bld/gcc/hc3bnbyc3hsf/lib/libgcc_s.so.1 (0x00007f12705df000)
	libquadmath.so.0 => /local/certik/bld/gcc/hc3bnbyc3hsf/lib/libquadmath.so.0 (0x00007f12703a2000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f127000d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f127100a000)
```
Most libraries are wrong unfortunately, so we need to pick one and investigate exactly how that could happen. I tested that just adding `-Wl,-rpath -Wl,/xx/lib` to `gcc` keeps appending to the rpath, e.g.:
```
certik@redhawk:/tmp$ g++ a.c -Wl,-rpath -Wl,/xx/lib
certik@redhawk:/tmp$ patchelf --print-rpath a.out
/local/certik/bld/gcc/lveg4hd6gebz/lib:/xx/lib
```
As you can see, gcc adds the correct rpath to the standard libs (`/local/certik/bld/gcc/lveg4hd6gebz/lib`) and then appends the requested rpath (`/xx/lib`), so I don't quite understand how the rpath could get erased, unless you use a tool like `patchelf`, which we don't use much.

**Comment by kiwifb** [comment]
Cmake sometimes strips rpath at install time.

**Comment by certik** [comment]
The weird thing is that it stripped the gcc's provided rpath, but puts other rpath in.

But how do you technically strip the rpath? I thought the only way to do that is through cmake.

**Comment by kiwifb** [comment]
I am not sure of the mechanics of cmake stripping. It shows a hole in my knowledge. However I think the symptom you are seeing show that gcc is not used for linking, ld must be directly called. That's what I am suspecting happens with libtools.

Those are my notes about cmake and rpath
```
RUNPATH with CMake

Occasionally cmake will not set runpath what ever the settings of CMAKE_SKIP_RPATH/CMAKE_SKIP_INSTALL_RPATH. 
Do not turn them ON in the hope it will work. It means the author of the package are inept at handling runpath and haven't made any provision for it in CMakeLists.txt. The following page (http://www.cmake.org/Wiki/CMake_RPATH_handling) is helpful. And basically for that case an invocation of ccmake would look like:

ccmake $SRC_DIR -DCMAKE_SKIP_BUILD_RPATH=FALSE -DCMAKE_BUILD_WITH_INSTALL_RPATH=FALSE -DCMAKE_INSTALL_RPATH="${LD_RUN_PATH}:${CMAKE_INSTALL_PREFIX}/lib" -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE
```
The cmake invocation may need some tweaking.

**Comment by certik** [comment]
Ah, I see --- and it seems `ld` comes from the system, not our gcc, so it cannot know about our path. Hm. How do we fix that?

**Comment by kiwifb** [comment]
Well I mentioned in the thread and Dag thought it would be a good idea, to wrap ld.  Unless you have a strange install of gcc it will call ld that's in the PATH. libtool and cmake will probably do that too - there are no reason for them to do otherwise (OK cmake could hardcode the ld it has used at install time but I doubt it).

**Comment by kiwifb** [comment]
Hum are you sure that for libginac the rpath is stripped? Could you get the output of "readelf -d" on it?

**Comment by ahmadia** [comment]
> Well I mentioned in the thread and Dag thought it would be a good idea,
to wrap ld. Unless you have a strange install of gcc it will call ld that's
in the PATH. libtool and cmake will probably do that too - there are no
reason for them to do otherwise (OK cmake could hardcode the ld it has used
at install time but I doubt it).

I also think that providing an ld wrapper where it's feasible is a very
good idea.  Most of the time, it's the link stage that we're interested in
modifying/intercepting, not the compiler.

**Comment by certik** [comment]
I could see now why the wrapper might be a good idea after all --- I didn't realize that cmake and libtool might be using `ld` directly.

@kiwifb here it is:
```
certik@redhawk:~/repos/hashstack/default$ readelf -d lib/libginac.so
...
 0x000000000000000f (RPATH)              Library rpath: [/local/certik/bld/cln/ac7u7rpiqkr4/lib:/local/certik/bld/cmake/eyyhg7azn7ys/lib:/local/certik/bld/patchelf/qqzlbpi7rek7/lib:/local/certik/bld/ginac/eoehzkrovwjk/lib:/local/certik/bld/cln/ac7u7rpiqkr4/lib]
```
As you can see, the gcc's rpath is gone, only Hashdist's rpaths remained.

**Comment by kiwifb** [comment]
Very curious my install logs seems to indicate that libginac is linked by g++ under gentoo. But ginac seems to want to do rpath itself as well. I feel like I miss a bit of the picture and that could bit us in the butt later on.

**Comment by certik** [comment]
That's right, we need to get to the bottom of this ---- we need to figure out the exact mechanism that removes the original rpath that gcc puts in (or if some other options cause gcc not to put the rpath in in the first place).

**Comment by kiwifb** [comment]
Ok. gcc -Wl,-rpath=path just crush the one from the spec which is not the behavior I get on ppc so the patch needs work.

**Comment by kiwifb** [comment]
Exactly the mistake I suspected. When I posted the original patch I made a note wondering if the rpath line needed to be one line lower. That's exactly what is needed.
```
diff -Naur i386.orig/gnu-user.h i386/gnu-user.h
--- i386.orig/gnu-user.h        2015-02-19 14:00:02.412911378 +1300
+++ i386/gnu-user.h     2015-02-20 14:07:31.791097520 +1300
@@ -79,7 +79,8 @@
     %{!static: \
       %{rdynamic:-export-dynamic} \
       -dynamic-linker %(dynamic_linker)} \
-      %{static:-static}}"
+      %{static:-static}} \
+      -rpath @@ARTIFACT@@/lib"
 
 #undef LINK_SPEC
 #define LINK_SPEC GNU_USER_TARGET_LINK_SPEC
diff -Naur i386.orig/gnu-user64.h i386/gnu-user64.h
--- i386.orig/gnu-user64.h      2015-02-19 14:00:02.412911378 +1300
+++ i386/gnu-user64.h   2015-02-20 14:07:03.091029363 +1300
@@ -63,7 +63,8 @@
       %{" SPEC_32 ":-dynamic-linker " GNU_USER_DYNAMIC_LINKER32 "} \
       %{" SPEC_64 ":-dynamic-linker " GNU_USER_DYNAMIC_LINKER64 "} \
       %{" SPEC_X32 ":-dynamic-linker " GNU_USER_DYNAMIC_LINKERX32 "}} \
-    %{static:-static}}"
+    %{static:-static}} \
+    -rpath @@ARTIFACT@@/lib"
 
 #undef LINK_SPEC
 #define LINK_SPEC GNU_USER_TARGET_LINK_SPEC
```
With that all the case of extra rpath should go away. The only thing left are the cases where cmake strip rpath :( [I am not sure wrapping ld would help with that, they have to be caught and sanitized] and ld is used directly which is not often.

**Comment by kiwifb** [comment]
And before posting I ate my own dog-food
```
fbissey@QCD-nzi3 ~/sandbox/local/bin $ ./gcc -Wl,-rpath=/usr/lib64 a.c
fbissey@QCD-nzi3 ~/sandbox/local/bin $ readelf -d a.out 

Dynamic section at offset 0xe18 contains 25 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/home/fbissey/sandbox/local/lib:/usr/lib64]
 0x000000000000000c (INIT)               0x4003f0
```

**Comment by ahmadia** [comment]
> And before posting I ate my own dog-food

@kiwifb - That makes you a good person :)

**Comment by certik** [comment]
@kiwifb thanks for figuring this out! I am going to try this tomorrow. However, can you explain to me how is it possible that you are getting different result for `gcc -Wl,-rpath=path` than I do? See the end of this issue description, copying here:
```
certik@redhawk:/tmp$ g++ a.c -Wl,-rpath -Wl,/xx/lib
certik@redhawk:/tmp$ patchelf --print-rpath a.out
/local/certik/bld/gcc/lveg4hd6gebz/lib:/xx/lib
```
and this is with the current patch. Could this be the difference between `-Wl,-rpath -Wl,/xx/lib` vs `-Wl,-rpath=/xx/lib`, or is that a difference between `g++ a.c -Wl,-rpath -Wl,/xx/lib` and `g++ -Wl,-rpath -Wl,/xx/lib a.c`? I will test this tomorrow. I need to be clear on this.

As far as cmake, if it really strips the rpath using ld directly, then we can report a bug, or perhaps provide a fix ourselves for Hashstack, and just ship "fixed" cmake, that doesn't strip the paths.

**Comment by kiwifb** [comment]
I am not sure which difference you are talking about. I didn't use hashdist to build the gcc with which I tested the patch if you are are worried about the rpath to gcc's libraries.

As for cmake the stripping is a feature. Let me be clearer about that.

Most cmake package with well developed CMakeList.txt won't strip your rpath.

Packages using cmake made by people who have no idea about rpath may strip your rpath.

As a standard option in cmake you will be offered
```
 CMAKE_SKIP_INSTALL_RPATH         OFF                                                                                                                                     
 CMAKE_SKIP_RPATH                 OFF                                                                                                                                     
```
You get these for free. Or almost see: http://www.cmake.org/Wiki/CMake_RPATH_handling#Common_questions
There is only one question and it is how you end up with stripped rpath. This is avoided by adding one line to CMakeList.txt and the magic cmake means that you can actually add it as a switch to a package lacking it.
```
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE
```

Why does cmake strip rpath. Apart from "because we can", it has flexibility in when in the build process to add the rpath. Most notably you may want different rpath when testing than when you install.

With libtool I have seen the testing situation handled by libtool generating a script that includes setting LD_LIBRARY_PATH. Note that this is one of the reasons I loath LD_LIBRARY_PATH.
Case in point: Octave (yes gnu octave the clone of matlab). I have build octave regularly on the cluster I take care of. Testing will always fail without a bit of love because libtool thinks it is a good idea to insert /usr/lib64 in LD_LIBRARY_PATH - think about it.

**Comment by certik** [comment]
@kiwifb I am reacting to your comment:

> gcc -Wl,-rpath=path just crush the one from the spec which is not the behavior I get on ppc so the patch needs work.

I am not able to reproduce this using the current hashstack's gcc. I tried all these:
```
certik@redhawk:/tmp$ g++ -Wl,-rpath -Wl,/xx/lib a.c && patchelf --print-rpath a.out
/local/certik/bld/gcc/lveg4hd6gebz/lib:/xx/lib
certik@redhawk:/tmp$ g++ a.c -Wl,-rpath -Wl,/xx/lib && patchelf --print-rpath a.out
/local/certik/bld/gcc/lveg4hd6gebz/lib:/xx/lib
certik@redhawk:/tmp$ g++ a.c -Wl,-rpath=/xx/lib && patchelf --print-rpath a.out
/local/certik/bld/gcc/lveg4hd6gebz/lib:/xx/lib
certik@redhawk:/tmp$ g++ -Wl,-rpath=/xx/lib a.c && patchelf --print-rpath a.out
/local/certik/bld/gcc/lveg4hd6gebz/lib:/xx/lib
```
And the rpath from the spec never gets erased.

So I am going to try your patch moving the `@@ARTIFACT@@` line down, but I don't see how it can fix anything. I'll keep you posted.

**Comment by certik** [comment]
Ha, I think it helped even with cmake!!!
```
certik@redhawk:~/repos/hashstack(w)$ ldd test/lib/libginac.so	linux-vdso.so.1 =>  (0x00007fff8a7ff000)
	libcln.so.6 => /local/certik/bld/cln/ac7u7rpiqkr4/lib/libcln.so.6 (0x00007f9a8c71a000)
	libstdc++.so.6 => /local/certik/bld/gcc/vfnflgljyg4l/lib/libstdc++.so.6 (0x00007f9a8c407000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9a8c168000)
	libgcc_s.so.1 => /local/certik/bld/gcc/vfnflgljyg4l/lib/libgcc_s.so.1 (0x00007f9a8bf52000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9a8bbbd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9a8cf7d000)
```
(We build ginac using cmake.)

**Comment by certik** [comment]
@ahmadia now I am facing a problem --- the only change is updated/fixed gcc, and I need to rebuild all packages, but hashdist doesn't recognize that anything got changed.

**Comment by ahmadia** [comment]
Does setting

CC=/local/certik/bld/gcc/vfnflgljyg4l/bin/gcc

in your profile work?

**Comment by certik** [comment]
@ahmadia ah yes, I think that would do. Even better, currently I do:
```
  PROLOGUE: |
    export PATH="/home/certik/repos/hashstack/hd_base/bin:$PATH"; export CC=gcc CXX=g++ FC=gfortran
```
So I think a better approach is to use the fact that
```
certik@redhawk:~/repos/hashstack(w)$ ll hd_base
lrwxrwxrwx 1 certik certik 38 Feb 20 10:36 hd_base -> /local/certik/bld/profile/bto56eplrk4v/
```
and use this:
```
  PROLOGUE: |
    export PATH="/local/certik/bld/profile/bto56eplrk4v/bin:$PATH"; export CC=gcc CXX=g++ FC=gfortran
```
That way if I patch gcc again, the profile hash will change.

**Comment by certik** [comment]
I just checked Trilinos (see my issue description above for the failures) and now it works:
```
certik@redhawk:~/repos/hashstack(w)$ ldd default/lib/libamesos.so
	linux-vdso.so.1 =>  (0x00007fff449ff000)
	libepetraext.so.11 => /local/certik/bld/trilinos/rouejztbcl3h/lib/libepetraext.so.11 (0x00007fabb9fef000)
	libepetra.so.11 => /local/certik/bld/trilinos/rouejztbcl3h/lib/libepetra.so.11 (0x00007fabb9c81000)
	libteuchosremainder.so.11 => /local/certik/bld/trilinos/rouejztbcl3h/lib/libteuchosremainder.so.11 (0x00007fabb9a7b000)
	libteuchosnumerics.so.11 => /local/certik/bld/trilinos/rouejztbcl3h/lib/libteuchosnumerics.so.11 (0x00007fabb9856000)
	libteuchoscomm.so.11 => /local/certik/bld/trilinos/rouejztbcl3h/lib/libteuchoscomm.so.11 (0x00007fabb957a000)
	libteuchosparameterlist.so.11 => /local/certik/bld/trilinos/rouejztbcl3h/lib/libteuchosparameterlist.so.11 (0x00007fabb902c000)
	libteuchoscore.so.11 => /local/certik/bld/trilinos/rouejztbcl3h/lib/libteuchoscore.so.11 (0x00007fabb8dd4000)
	libtriutils.so.11 => /local/certik/bld/trilinos/rouejztbcl3h/lib/libtriutils.so.11 (0x00007fabb8b82000)
	libopenblas.so.0 => /local/certik/bld/openblas/2wc6yoy6i5m5/lib/libopenblas.so.0 (0x00007fabb7cb3000)
	libmpichcxx.so.10 => /local/certik/bld/mpi/s3onu7dmekim/lib/libmpichcxx.so.10 (0x00007fabb7a90000)
	libmpich.so.10 => /local/certik/bld/mpi/s3onu7dmekim/lib/libmpich.so.10 (0x00007fabb761e000)
	libopa.so.1 => /local/certik/bld/mpi/s3onu7dmekim/lib/libopa.so.1 (0x00007fabb741d000)
	libmpl.so.1 => /local/certik/bld/mpi/s3onu7dmekim/lib/libmpl.so.1 (0x00007fabb7218000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fabb6ff5000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fabb6dd8000)
	libstdc++.so.6 => /local/certik/bld/gcc/vfnflgljyg4l/lib/libstdc++.so.6 (0x00007fabb6ac5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fabb6841000)
	libgcc_s.so.1 => /local/certik/bld/gcc/vfnflgljyg4l/lib/libgcc_s.so.1 (0x00007fabb662b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fabb6296000)
	libmpichf90.so.10 => /local/certik/bld/mpi/s3onu7dmekim/lib/libmpichf90.so.10 (0x00007fabb6094000)
	libgfortran.so.3 => /local/certik/bld/gcc/vfnflgljyg4l/lib/libgfortran.so.3 (0x00007fabb5d76000)
	libquadmath.so.0 => /local/certik/bld/gcc/vfnflgljyg4l/lib/libquadmath.so.0 (0x00007fabb5b39000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fabba630000)
```
I am now rebuilding the whole stack and we'll see.

**Comment by certik** [comment]
@kiwifb, thanks a lot for the fix. Indeed it fixed everything. It looks like I can now use the Hashstack's installed gcc as a first class compiler, essentially I just put this into my .bashrc:
```bash
export HASHSTACK=$HOME/repos/hashstack/hd_base
export PATH="$HASHSTACK/bin:$PATH"
export MANPATH="$HASHSTACK/man:$MANPATH"
export CC=gcc CXX=g++ FC=gfortran
```
No `LD_LIBRARY_PATH` fiddling, and the `gcc` works exactly as expected, just like if it was a systemwide compiler installed in `/usr/bin`.

Thanks @ahmadia for the tip, it worked.
