### ISSUE TITLE
shippable (Linux) pycgal build is failing 

### ISSUE THREAD

**Issue by ahmadia** [hashdist/hashstack#650]
See: https://app.shippable.com/builds/54e670aa65be240e00671b89

```
[pycgal] Building pycgal/jkohzc6fx4ga, follow log with:
[pycgal] tail -f /home/shippable/.hashdist/tmp/pycgal-jkohzc6fx4ga/build.log
[pycgal|ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
[pycgal|ERROR] command failed (code=1); raising
make: *** [/home/shippable/workspace/src/github.com/erdc-cm/proteus/linux2/artifact.json] Error 127
```

The shippable profile is here: https://github.com/erdc-cm/proteus/blob/master/.shippable-profile.yaml

**Comment by ahmadia** [comment]
cc @cekees

**Comment by certik** [comment]
From the error there is not much that you can do. You need to use the same hack that we use for Travis so that you can see the actual error.
