### ISSUE TITLE
mpi4py fails with host-cython

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#653]
This was reported to me today:

    2015/02/20 13:32:33 - INFO: [package:run_job] running install
    2015/02/20 13:32:33 - INFO: [package:run_job] running build
    2015/02/20 13:32:33 - INFO: [package:run_job] running build_src
    2015/02/20 13:32:33 - INFO: [package:run_job] ********************************************************************************
    2015/02/20 13:32:33 - INFO: [package:run_job]
    2015/02/20 13:32:33 - INFO: [package:run_job]  You need to generate C source files with Cython!!
    2015/02/20 13:32:33 - INFO: [package:run_job]  Download and install Cython <http://www.cython.org>
    2015/02/20 13:32:33 - INFO: [package:run_job]
    2015/02/20 13:32:33 - INFO: [package:run_job] ********************************************************************************
    2015/02/20 13:32:33 - INFO: [package:run_job] error: requires Cython>=0.15
    2015/02/20 13:32:33 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
    2015/02/20 13:32:33 - ERROR: [package:run_job] command failed (code=1); raising

It looks like we link to the wrong file in [host-cython.yaml](https://github.com/hashdist/hashstack/blob/master/pkgs/host-cython.yaml). I think this is correct:

    diff --git a/pkgs/host-cython.yaml b/pkgs/host-cython.yaml
    index 927ae95..eb2c03c 100644
    --- a/pkgs/host-cython.yaml
    +++ b/pkgs/host-cython.yaml
    @@ -2,7 +2,7 @@ build_stages:
       - handler: bash
         bash: |
           mkdir -p ${ARTIFACT}/{{python_site_packages_rel}}
    -      ln -s {{python_host_packages}}/cython ${ARTIFACT}/{{python_site_packages_rel}}
    +      ln -s {{python_host_packages}}/cython.py ${ARTIFACT}/{{python_site_packages_rel}}
     
     profile_links:

**Comment by ahmadia** [comment]
That makes a bit more sense.  I'm not very familiar with the host Python
packages setup.

**Comment by johannesring** [comment]
Sorry, the problem was simply that the he didn't have cython installed. Anyway, I will make a pull request that fixes the broken link.

**Comment by johannesring** [comment]
Fixed in #664.
