### ISSUE TITLE
"ssh: Could not resolve hostname" when installing FEniCS

### ISSUE THREAD

**Issue by funsim** [hashdist/hashstack#699]
I am trying to install FEniCS via Hashdist on a MacOSX Yosemite 10.10.2 machine via the 

```bash
curl -s http://fenicsproject.org/fenics-install.sh | bash
```

However, the installation hangs when installing parmetis. The log says:

```bash
rainier:fenics kthyng$ tail -f /Users/kthyng/.hashdist/tmp/parmetis-zcwacvmufcjo-2/build.log
2015/03/19 16:35:12 - INFO: [package:run_job] Install the project...
2015/03/19 16:35:12 - INFO: [package:run_job] /Users/kthyng/.hashdist/bld/cmake/gji2dnrnee33/bin/cmake -P cmake_install.cmake
2015/03/19 16:35:12 - INFO: [package:run_job] -- Install configuration: ""
2015/03/19 16:35:12 - INFO: [package:run_job] -- Installing: /Users/kthyng/.hashdist/bld/parmetis/zcwacvmufcjo/include/parmetis.h
2015/03/19 16:35:12 - INFO: [package:run_job] -- Installing: /Users/kthyng/.hashdist/bld/parmetis/zcwacvmufcjo/lib/libparmetis.dylib
2015/03/19 16:35:12 - INFO: [package:run_job] -- Installing: /Users/kthyng/.hashdist/bld/parmetis/zcwacvmufcjo/bin/ptest
2015/03/19 16:35:12 - INFO: [package:run_job] -- Installing: /Users/kthyng/.hashdist/bld/parmetis/zcwacvmufcjo/bin/mtest
2015/03/19 16:35:12 - INFO: [package:run_job] -- Installing: /Users/kthyng/.hashdist/bld/parmetis/zcwacvmufcjo/bin/parmetis
2015/03/19 16:35:12 - INFO: [package:run_job] -- Installing: /Users/kthyng/.hashdist/bld/parmetis/zcwacvmufcjo/bin/pometis
2015/03/19 16:35:12 - INFO: [package:run_job] ssh: Could not resolve hostname rainier: nodename nor servname provided, or not known
```

The machine has internet connection. For some reason the installation is trying to ssh into ```rainier``` , which is the machines name?

**Comment by ahmadia** [comment]
Hi @funsim.  Can you give me a full build log?  I've never seen this one before, but it sounds like whatever SSH the build is trying to use (and for whatever reason), is broken in some way.  The file lives here: /Users/kthyng/.hashdist/tmp/parmetis-zcwacvmufcjo-2/build.log

**Comment by kthyng** [comment]
Hey @ahmadia here it is: https://gist.github.com/kthyng/b94bd8de8ae2ccdce1a7

**Comment by ahmadia** [comment]
@kthyng - If I had to hazard a guess, HashDist is trying to run the `parmetis` tests to verify the installation, and the MPI is failing due to a gethostbyname error.  The easiest way to fix this is to modify the `/etc/hosts` file and make sure there's a line like this in there:

```
127.0.0.1	rainier
```

I don't know why the MPI on your system is unhappy/broken.  How is the `rainier` name being assigned?  Is that something you named your laptop?  OS X should correctly resolve that hostname...

**Comment by ahmadia** [comment]
Oh, and this probably goes without saying when messing around in `/etc/`, but make a backup of the `/etc/hosts` file and don't delete any lines in there, just add a new one.

**Comment by kthyng** [comment]
Awesome! It's moved past that part now. Thanks Aron!
