### ISSUE TITLE
Missing build dependency on libxml2 for mpich package 

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#701]
@alogg [reported](http://fenicsproject.org/pipermail/fenics-support/2015-March/001399.html) today the following error when building `mpich`:

    2015/03/25 07:49:43 - INFO: [package:run_job] topology-xml-libxml.c:16:10: fatal error: 'libxml/parser.h' file not found

The fix was to add `libxml2` to the build dependencies for `mpich`. I will prepare a pull request.

**Comment by memmett** [comment]
I think the mpich code is just missing some `ifdef` guards.  Perhaps this
would be better addressed upstream instead?  @ahmedia and I stumbled upon
this in November too.

**Comment by johannesring** [comment]
Fixed in #702.
