### ISSUE TITLE
OpenBLAS inconspicuously threading

### ISSUE THREAD

**Issue by blechta** [hashdist/hashstack#717]
By default OpenBLAS is configured to use threads, see https://github.com/xianyi/OpenBLAS/wiki/faq#multi-threaded. On Intel hyper-threading machines, it spawns two threads per core which is not anticipated behaviour in almost any situation.

Possible resolution would be to configure OpenBLAS with `USE_THREAD=0`. Alternatively, it could be configured with threads but exporting `OPENBLAS_NUM_THREADS=1` by default in the case that there is some interest using built-in thread support.

In DOLFIN we have encountered [serious performance regression](http://fenicsproject.org/pipermail/fenics/2015-March/002648.html) and this was even sequential application on empty machine. Running parallel application with number of processes or threads (spawned outside of uBLAS) equal to number of cores could result in a much more serious disaster. [The fix has been implemented here.](https://bitbucket.org/fenics-project/fenics-developer-tools/commits/7091d2fcde21054c0548647ad862069b68c7f044#comment-1807762)

**Comment by certik** [comment]
We should expose this feature (i.e. whether to use threads or not) as a parameter, that the user can set in his or her profile.

**Comment by blechta** [comment]
I think that threading disabled should be the default.

**Comment by johannesring** [comment]
Fixed in #718.
