### ISSUE TITLE
netcdf4 tarball removed

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#719]
It looks like the `netcdf-4.3.2.tar.gz` tarball has been removed from ftp://ftp.unidata.ucar.edu/pub/netcdf/. This results in errors from Travis like [this](https://travis-ci.org/hashdist/hashstack/jobs/57764055) and [this](https://travis-ci.org/hashdist/hashstack/jobs/57775604). Should we just upgrade to the latest release (4.3.3.1)?

**Comment by certik** [comment]
Yes, we should.
