### ISSUE TITLE
Case sensitive filenames fail with `git reset --hard` on OS X 10.10

### ISSUE THREAD

**Issue by certik** [hashdist/hashstack#770]
Look at this weird behavior on OS X 10.10
```
$ git st
On branch gcc_osx
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   pkgs/gdal.yaml

$ git reset --hard 
HEAD is now at 6a0c174 Merge pull request #769 from hashdist/cmake_osx
$ git st
On branch gcc_osx
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   pkgs/GDAL.yaml

$ git reset --hard 
HEAD is now at 6a0c174 Merge pull request #769 from hashdist/cmake_osx
$ git st
On branch gcc_osx
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   pkgs/gdal.yaml

```
That is:

* the `git reset --hard` never gets rid of the change
* the modified file oscillates between `pkgs/gdal.yaml` and `pkgs/GDAL.yaml` **indefinitely**

Any ideas how to fix this?

**Comment by cekees** [comment]
Use  linux:) Sorry, I can only remember the outrage I felt when I first  discovered that os x's default file system is case insensitive but case preserving.  Does  get checkout not work either? I guess we need to make GDAL.yaml gdal-python.yaml or  something like  that. I suspect this is my fault.

**Comment by certik** [comment]
Yeah, it got broken by 5aa0a7f25095667665a06c5d97e05cdc23ba5f5e, i.e. after I updated my master.

I can't use linux on my laptop. I could use Windows, but I expect even worse experience. By now, I got most of the things fixed, that I can actually use OS X to do work.

**Comment by cekees** [comment]
BTW, I think you can just change the file system to something besides HFS+ if you really wanted  to make it case sensitive, but I found that the problem really doesn't arise all that much.

**Comment by certik** [comment]
I don't have root access, so I can't.
