### ISSUE TITLE
flufl.lock should be added as runtime dependency of Instant

### ISSUE THREAD

**Issue by blechta** [hashdist/hashstack#800]
[`flufl.lock`](https://gitlab.com/warsaw/flufl.lock) implements file locks on NFS where Python built-in module `fcntl` does not work. See also [Instant README](https://bitbucket.org/fenics-project/instant/src/master/README).

**Comment by johannesring** [comment]
Yes, that would be good.

I tried to make a package with `hit skeleton-pypi flufl.lock` and then build this simple profile:

    extends:                     
    - file: linux.yaml           
                             
    packages:                    
      launcher:                  
      python:                    
        link: shared             
      flufl.lock:               

The `flufl.lock` package was built successfully but HashDist failed to generate the profile:

    [profile] Building profile/3t6k2hwwhhoy, follow log with:
    [profile]   tail -f /home/johannr/.hashdist/tmp/profile-3t6k2hwwhhoy/build.log
    [CRITICAL] Uncaught exception:
    [CRITICAL] Traceback (most recent call last):
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/cli/main.py", line 202, in help_on_exceptions
    [CRITICAL]     return func(*args, **kw)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/cli/main.py", line 174, in command_line_entry_point
    [CRITICAL]     retcode = args.subcommand_handler(ctx, args)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/cli/frontend_cli.py", line 53, in run
    [CRITICAL]     self.profile_builder_action()
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/cli/frontend_cli.py", line 112, in profile_builder_action
    [CRITICAL]     artifact_id, artifact_dir = self.builder.build_profile(self.ctx.get_config())
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/spec/builder.py", line 155, in build_profile
    [CRITICAL]     return self.build_store.ensure_present(profile_build_spec, config)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/build_store.py", line 379, in ensure_present
    [CRITICAL]     artifact_dir = builder.build(config, keep_build)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/build_store.py", line 554, in build
    [CRITICAL]     self.build_to(artifact_dir, config, keep_build)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/build_store.py", line 573, in build_to
    [CRITICAL]     self.run_build_commands(build_dir, artifact_dir, env, config)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/build_store.py", line 632, in run_build_commands
    [CRITICAL]     temp_dir=job_tmp_dir, debug=self.debug)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/run_job.py", line 342, in run_job
    [CRITICAL]     executor.run_command_list(assembled_commands, env, ())
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/run_job.py", line 615, in run_command_list
    [CRITICAL]     self.run_node(command_node, env, pos)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/run_job.py", line 501, in run_node
    [CRITICAL]     getattr(self, 'handle_%s' % type)(node, env, node_pos)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/run_job.py", line 516, in handle_prepend_path
    [CRITICAL]     node['prepend_path'], 'prepend', os.path.pathsep)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/run_job.py", line 530, in handle_env_mod
    [CRITICAL]     value = self.substitute(value, env)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/run_job.py", line 429, in substitute
    [CRITICAL]     return substitute(x, env)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/core/run_job.py", line 376, in substitute
    [CRITICAL]     return Template(x).substitute(env)
    [CRITICAL]   File "/usr/lib/python2.7/string.py", line 176, in substitute
    [CRITICAL]     return self.pattern.sub(convert, self.template)
    [CRITICAL]   File "/usr/lib/python2.7/string.py", line 173, in convert
    [CRITICAL]     self._invalid(mo)
    [CRITICAL]   File "/usr/lib/python2.7/string.py", line 146, in _invalid
    [CRITICAL]     (lineno, colno))
    [CRITICAL] BuildFailedError: ValueError: Invalid placeholder in string: line 1, col 1
    [INFO] 
    [CRITICAL] This exception has not been translated to a human-friendly error message,
    [CRITICAL] please file an issue at https://github.com/hashdist/hashdist/issues pasting
    [CRITICAL] this stack trace.

Is it not possible to have a `.` in the package name? @dagss?

**Comment by dagss** [comment]
Yes, please avoid dots in package names. Make it "flufl_lock"

Dag Sverre

**Comment by johannesring** [comment]
@dagss - ok, thanks!
