### ISSUE TITLE
scotch is missing zlib in build dependencies

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#810]
2015/07/15 14:32:52 - INFO: [package:run_job] running [u'/bin/bash', '_hashdist/build.sh']
    2015/07/15 14:32:52 - INFO: [package:run_job] environment:
    2015/07/15 14:32:52 - INFO: [package:run_job]   {'ARTIFACT': u'/root/.hashdist/bld/scotch/qaholoekwukv',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'BASH': u'/bin/bash',
    2015/07/15 14:32:52 - INFO: [package:run_job]    u'BISON_DIR': u'/root/.hashdist/bld/bison/jri2642x26uh',
    2015/07/15 14:32:52 - INFO: [package:run_job]    u'BISON_ID': u'bison/jri2642x26uh23m4dmuubodq6wbimuib',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'BUILD': u'/root/.hashdist/tmp/scotch-qaholoekwukv',
    2015/07/15 14:32:52 - INFO: [package:run_job]    u'FLEX_DIR': u'/root/.hashdist/bld/flex/eeduf457bgf4',
    2015/07/15 14:32:52 - INFO: [package:run_job]    u'FLEX_ID': u'flex/eeduf457bgf4ywsckky6ak5luhqckn2g',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'HASHDIST_CPU_COUNT': '4',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'HDIST_CONFIG': '{"gc_roots":"/root/.hashdist/gcroots","build_stores":[{"dir":"/root/.hashdist/bld"}],"source_caches":[{"dir":"/root/.hashdist/src"}],"cache":"/root/.hashdist/cache","build_temp":"/root/.hashdist/tmp"}',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'HDIST_IMPORT': u'bison/jri2642x26uh23m4dmuubodq6wbimuib flex/eeduf457bgf4ywsckky6ak5luhqckn2g mpi/gmkx3ftk3tz2q6qreifxplulowzcim5h patchelf/k3rloj265ogtl4dmmmbmyt34dnffryka',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'HDIST_IMPORT_PATHS': u'/root/.hashdist/bld/bison/jri2642x26uh:/root/.hashdist/bld/flex/eeduf457bgf4:/root/.hashdist/bld/mpi/gmkx3ftk3tz2:/root/.hashdist/bld/patchelf/k3rloj265ogt',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'HDIST_VIRTUALS': '',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'MPICC': u'/root/.hashdist/bld/mpi/gmkx3ftk3tz2/bin/mpicc',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'MPICXX': u'/root/.hashdist/bld/mpi/gmkx3ftk3tz2/bin/mpic++',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'MPIEXEC': u'/root/.hashdist/bld/mpi/gmkx3ftk3tz2/bin/mpiexec',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'MPIF77': u'/root/.hashdist/bld/mpi/gmkx3ftk3tz2/bin/mpif77',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'MPIF90': u'/root/.hashdist/bld/mpi/gmkx3ftk3tz2/bin/mpif90',
    2015/07/15 14:32:52 - INFO: [package:run_job]    u'MPI_DIR': u'/root/.hashdist/bld/mpi/gmkx3ftk3tz2',
    2015/07/15 14:32:52 - INFO: [package:run_job]    u'MPI_ID': u'mpi/gmkx3ftk3tz2q6qreifxplulowzcim5h',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'PATCHELF': u'/root/.hashdist/bld/patchelf/k3rloj265ogt/bin/patchelf',
    2015/07/15 14:32:52 - INFO: [package:run_job]    u'PATCHELF_DIR': u'/root/.hashdist/bld/patchelf/k3rloj265ogt',
    2015/07/15 14:32:52 - INFO: [package:run_job]    u'PATCHELF_ID': u'patchelf/k3rloj265ogtl4dmmmbmyt34dnffryka',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'PATH': u'/root/.hashdist/bld/mpi/gmkx3ftk3tz2/bin:/root/.hashdist/bld/flex/eeduf457bgf4/bin:/root/.hashdist/bld/bison/jri2642x26uh/bin:/usr/bin:/bin',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'PKG_CONFIG_PATH': u'/root/.hashdist/bld/mpi/gmkx3ftk3tz2/lib/pkgconfig',
    2015/07/15 14:32:52 - INFO: [package:run_job]    'PWD': u'/root/.hashdist/tmp/scotch-qaholoekwukv'}
    2015/07/15 14:32:52 - INFO: [package:run_job] make: Entering directory '/root/.hashdist/tmp/scotch-qaholoekwukv/src'
    2015/07/15 14:32:52 - INFO: [package:run_job] (cd libscotch ;      make VERSION=6 RELEASE=0 PATCHLEVEL=0 ptscotch && make ptinstall)
    2015/07/15 14:32:52 - INFO: [package:run_job] make[1]: Entering directory '/root/.hashdist/tmp/scotch-qaholoekwukv/src/libscotch'
    2015/07/15 14:32:52 - INFO: [package:run_job] make CC="/root/.hashdist/bld/mpi/gmkx3ftk3tz2/bin/mpicc" CCD="/root/.hashdist/bld/mpi/gmkx3ftk3tz2/bin/mpicc"	\
    2015/07/15 14:32:52 - INFO: [package:run_job] 				scotch.h				\
    2015/07/15 14:32:52 - INFO: [package:run_job] 				scotchf.h				\
    2015/07/15 14:32:52 - INFO: [package:run_job] 				libscotch.a				\
    2015/07/15 14:32:52 - INFO: [package:run_job] 				libscotcherr.a			\
    2015/07/15 14:32:52 - INFO: [package:run_job] 				libscotcherrexit.a
    2015/07/15 14:32:52 - INFO: [package:run_job] make[2]: Entering directory '/root/.hashdist/tmp/scotch-qaholoekwukv/src/libscotch'
    2015/07/15 14:32:52 - INFO: [package:run_job] /root/.hashdist/bld/mpi/gmkx3ftk3tz2/bin/mpicc -fPIC -O3 -DCOMMON_FILE_COMPRESS_GZ -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_RENAME -Drestrict=__restrict -DSCOTCH_VERSION=6 -DSCOTCH_RELEASE=0 -DSCOTCH_PATCHLEVEL=0 dummysizes.c -o dummysizes -lz -lm -lrt
    2015/07/15 14:32:52 - INFO: [package:run_job] /usr/bin/ld: cannot find -lz
    2015/07/15 14:32:52 - INFO: [package:run_job] collect2: error: ld returned 1 exit status
    2015/07/15 14:32:52 - INFO: [package:run_job] make[2]: *** [dummysizes] Error 1
    2015/07/15 14:32:52 - INFO: [package:run_job] Makefile:2911: recipe for target 'dummysizes' failed
    2015/07/15 14:32:52 - INFO: [package:run_job] make[2]: Leaving directory '/root/.hashdist/tmp/scotch-qaholoekwukv/src/libscotch'
    2015/07/15 14:32:52 - INFO: [package:run_job] Makefile:55: recipe for target 'scotch' failed
    2015/07/15 14:32:52 - INFO: [package:run_job] make[1]: *** [scotch] Error 2
    2015/07/15 14:32:52 - INFO: [package:run_job] make[1]: Leaving directory '/root/.hashdist/tmp/scotch-qaholoekwukv/src/libscotch'
    2015/07/15 14:32:52 - INFO: [package:run_job] Makefile:98: recipe for target 'ptscotch' failed
    2015/07/15 14:32:52 - INFO: [package:run_job] make: *** [ptscotch] Error 2
    2015/07/15 14:32:52 - INFO: [package:run_job] make: Leaving directory '/root/.hashdist/tmp/scotch-qaholoekwukv/src'
    2015/07/15 14:32:52 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 2
    2015/07/15 14:32:52 - ERROR: [package:run_job] command failed (code=2); raising

**Comment by jcftang** [comment]
closing this as there is now a fix that is merged
