### ISSUE TITLE
Change location of folder  /.hashdist in installation

### ISSUE THREAD

**Issue by srobertp** [hashdist/hashstack#812]
I am attempting to install the proteus (https://github.com/erdc-cm/proteus) package which uses hashdist to construct all the dependencies on proteus on a many cored "supercomputer"  available on my local network through ssh.  The problem is that when I have ssh'd into the supercomputer, I have two "home" directories available.  One is the normal home `u/srobertp` on my computer and the other is home for the supercomputer `w/srobertp` .   The environment variable $HOME is by default set to the local home `u/srobertp` but I want to have the `/.hashdist` folder that contains all the dependencies installed at `w/srobertp` instead of at $HOME.  

Is there a way to specify the install directory of the `/.hashdist` folder short of changing my $HOME variable to point to that location?  Something like setting a variable HDIST_HOME  or HDIST_CONFIG?  I can't find any documentation on how this could be done.

**Comment by ahmadia** [comment]
Sort of.  You can't install the location of `~/.hashdist/config.yaml`, but the directories for source, build, etc... are all specified in that profile and can be placed elsewhere.

**Comment by srobertp** [comment]
Would it be difficult to add support for changing the install location of ~/.hashdist/? 

Or alternatively what would be the process of moving the other folders in ~/.hashdist/ to say `w/srobertp/.hashdist/` ?  I am not sure I follow what you mean by "in that profile and can be placed elsewhere"?  Do I have to do that manually or is there a set of variables that I can specify somewhere?

**Comment by ahmadia** [comment]
This is a question for https://github.com/hashdist/hashdist, not hashstack.

See https://github.com/hashdist/hashdist/blob/master/hashdist/formats/config.example.yaml (or your own config.yaml) for modifiable parameters.

**Comment by srobertp** [comment]
@ahmadia thanks!  I will move over to the other group with the first question and I see what needs to be done in the second.

**Comment by cekees** [comment]
As long as you don't have multiple platforms using `u/srobertp` and only want to make sure storage  on `w/srobertp` is used, then modifying config.yaml is the way to go. The paths you need  to change are in config.yaml as `./bld`, `./src`, etc. You should just be able to give  them the full paths to directories on `w/srobertp`.

At first  I thought you were  in the other case, that is, where `u/srobertp` is  mounted  on multiple  platforms as your  home directory. There is a global option for directly setting the config file (`--config-file`), but I haven't used it.

**Comment by dagss** [comment]
A patch to read config file from environment variable (same meaning as `--config-file` CLI option, with CLI option overriding it) would be accepted to Hashdist, the place to look is hashdist.cli.main.
