### ISSUE TITLE
native blas/lapack/mpi support?

### ISSUE THREAD

**Issue by davydden** [hashdist/hashstack#865]
What is the status of blas support in hashdist? Can one use MKL, for example, with GCC, or system provided blas/lapack (CentOS, Ubuntu, OS-X)?

Trilinos seems to be using [hard-coded blas](https://github.com/hashdist/hashstack/blob/master/pkgs/trilinos.yaml#L33) whereas Petsc builds against `blas` [dependency](https://github.com/hashdist/hashstack/blob/master/pkgs/petsc/petsc.yaml#L3), but it's not clear to me what will it be at the end.

I suppose MPI is supported natively just fine (one does not have to compile open-mpi).

**Comment by ahmadia** [comment]
Host BLAS, LAPACK, and MPI are basically supported, see these packages for an example: 

* https://github.com/hashdist/hashstack/blob/master/pkgs/host-blas.yaml
* https://github.com/hashdist/hashstack/blob/master/pkgs/host-acml-blas.yaml

I'm not sure anybody has put in MKL support, but it wouldn't be hard.

See the examples sections for a couple of different ways that folks have specified and met the BLAS dependencies.

**Comment by davydden** [comment]
so when there is `build: [blas]`, how is it resolved? does it end up using https://github.com/hashdist/hashstack/blob/master/pkgs/host-blas.yaml ? just trying to understand how this sort of things are handled in hashdist.

**Comment by davydden** [comment]
and more importantly, how the user can choose which blas he wants: system-provided or, say, openblas?

**Comment by ahmadia** [comment]
A user sets the `use` flag in their profile to switch to a different `blas`.  There's an example with `mpi` in  https://hashdist.readthedocs.org/en/latest/specs.html

**Comment by cekees** [comment]
Those  are the examples  I'd  point to as well. Though there is some mkl support in a few of the stable/supercomputer_name  branches, none of it is general enough to push to  master as a host-mkl-blas package.  It might be possible  to use libmkl_rt to implement general host-mkl packages: https://software.intel.com/en-us/articles/a-new-linking-model-single-dynamic-library-mkl_rt-since-intel-mkl-103

**Comment by davydden** [comment]
i see... thanks a lot for the answers!
