### ISSUE TITLE
openblas parallel build typo and incorrect core count

### ISSUE THREAD

**Issue by cekees** [hashdist/hashstack#867]
@mbareford reported that the openblas build was asking for more processors than available on the login nodes of an HPC platform. I was looking at the opeblas pkg, and there appears to be a typo (HASDIST):
https://github.com/hashdist/hashstack/blob/master/pkgs/openblas.yaml#L34

I also would have thought that hashdist does serial builds of the `-j` option is not given.  Does it guess the number or cores?

**Comment by ahmadia** [comment]
I think hashdist uses `-j` by default when calling make.  I thought it didn't need a number of cores specified, but I think @certik may have tweaked this?

**Comment by johannesring** [comment]
In this case, the `-j` option is still given, but without a number since the mistyped `${HASDIST_CPU_COUNT}` variable will be empty. See `man make`:

``` man
      -j [jobs], --jobs[=jobs]
            Specifies the number of jobs (commands) to run simultaneously.  If
            there is more than one -j option, the last one is  effective.   If
            the  -j  option  is given without an argument, make will not limit
            the number of jobs that can run simultaneously.
```

**Comment by cekees** [comment]
I see, it's make itself that is using too many jobs due to the typo. I will fix the typo and verify that the issue goes away.
