### ISSUE TITLE
unify usage of blas/lapack in packages

### ISSUE THREAD

**Issue by davydden** [hashdist/hashstack#871]
I think it would be nice to unify the usage of blas/lapack in packages. For example, `trilinos` is currently built agaisnt `openblas`, whereas it actually can be easily built against whatever, including system's blas/lapack and also MKL. 

One option is to put in each and every `.yaml` some options like `with-openblas`, `with-host-blas`, `with-mkl` and pass different arguments to configure depending on what is chosen. This might be difficult to maintain, but that's what is done in [macports](www.macports.org).

What we do [here with Linuxbrew](https://github.com/davydden/homebrew-dealiisuite/blob/master/requirements/blas_requirement.rb) is to a) do not distinguish between blas and lapack; b) user input of `names` (`blas;lapack` or `mkl_x;mkl_y;mkl_z` or `openblas`); c) user input of lib dir (i.e. `$MKLROOT/lib64`); d) user input of include dir (i.e. `$MKLROOT/include`); (b-d) have some default fall-back strategy, i.e. use openblas and set up those variables accordingly.

So far that scheme works fine for some basic scientific software related to PDEs: `petsc`, `slepc`, `trilinos`, `p4est`, `parmetis`, `deal.ii`.

Note that in some cases the package's configure system can pick up blas/lapack without extra troubles, but generally the way blas/lapack is provded is very different:

1. library names (space/semicolon separated) + dir: [Hypre](https://github.com/davydden/homebrew-science/blob/mkl_dealii/hypre.rb#L39-L45), [Trilinos](https://github.com/davydden/homebrew-science/blob/mkl_dealii/trilinos.rb#L115-L120)
2. ldflags : [Superlu_dist](https://github.com/davydden/homebrew-science/blob/mkl_dealii/superlu_dist.rb#L31), [scalapack](https://github.com/davydden/homebrew-science/blob/mkl_dealii/scalapack.rb#L28-L29), [mumps](https://github.com/davydden/homebrew-science/blob/mkl_dealii/mumps.rb#L107-L108), [p4est](https://github.com/davydden/homebrew-science/blob/mkl_dealii/p4est.rb#L32)
3. full path (space/semicolon separated) : [Petsc](https://github.com/davydden/homebrew-science/blob/mkl_dealii/petsc.rb#L92-L93), [deal.II](https://github.com/davydden/homebrew-science/blob/mkl_dealii/dealii.rb#L58-L62) 

In case of `hashdist` one could probably put these things in parameters in a same way it is done for `host-mpi` and `host-cmake`:
```
  HOST_MPICC: /usr/bin/mpicc
  HOST_MPICXX: /usr/bin/mpic++
  HOST_MPIF77: /usr/bin/mpif77
  HOST_MPIF90: /usr/bin/mpif90
  HOST_MPIEXEC: /usr/bin/mpiexec
  HOST_CMAKE: /usr/bin/cmake
```
But then that would require to make each package kind of agnostic to what the user chose in 
````
   blas:
     use: xyz
  lapack:
     use: zyx
```
I don't know if inside `.yaml` one can check if `blas` was set to `use: openblas` or `use: host-blas` and act accordingly. If that's possible, for particular scenarios one could ignore setting up blas/lapack if the configuration system of a package is known to pick it up automatically.

Ideally, the choice of blas/lapack should be done in one place and then used everywhere without a need specify `build with xyz`.

Anyway, since `hashdist/hashstack` is still in beta i thought you may consider giving this issue a thought 
and perhaps consider introducing some changes to make it more flexible with regards to switching between different blas/lapack (MKL, system-provided, openblas, atlas, gotoblas, etc).

**Comment by johannesring** [comment]
When the [new parameter system](https://github.com/hashdist/hashdist/pull/339) is merged into HashDist, you can do things like `when: lapack.kind == 'openblas'`. I have been working on moving the packages to the new parameter system in the [parameters](https://github.com/hashdist/hashstack/tree/parameters) branch in HashStack. See for instance [hypre.yaml](https://github.com/hashdist/hashstack/blob/parameters/pkgs/hypre.yaml) and [trilinos.yaml](https://github.com/hashdist/hashstack/blob/parameters/pkgs/trilinos.yaml). I particularly like that I can use a pure yaml file (no need for a .py file) for DOLFIN with the new parameter system ([dolfin.yaml](https://github.com/hashdist/hashstack/blob/parameters/pkgs/dolfin/dolfin.yaml)).

Unfortunately, things are starting to get outdated as we keep making changes to HashStack master. I talked to @dagss about this earlier this week and we would like to try to merge this in soon.

**Comment by davydden** [comment]
`when: lapack.kind =='openblas'` looks good! That will certainly cover `openblas` and `blas`. 

I suppose for things like `MKL` one could add `when: lapack.kind =='mkl'` assuming that there are some parameters specified by the user in `parameters:` section and something like `host-mkl.yaml`? I don't know if in all cases MKL can be boiled down to `mkl_intel_lp64;mkl_sequential;mkl_core` sitting in `${MKLROOT}/lib/intel64` but the problem somewhat stays as different packages would like that info differently. 

As far as I recall the same problem will apply for `atlas` where one has several libraries. Of course, if you will build `atlas` inside `hashdist` you will know which libraries are there. However when it is available outside of hashdist, then it's similar to MKL where one need to work with a number of libraries and feed them to packages in a different manner.

Do you think one can handle this issue, ie. when blas/lapack is scattered among a number of libraries, somehow specified by the user.

**Comment by davydden** [comment]
p.s. if you have a solution in mind i can test it on CentOS cluster with OpenMPI and MKL. There's no other blas available there.

**Comment by johannesring** [comment]
I think we should be able to handle most of these cases with the new parameter system. We can do things like `{{' '.join(['-l' + l for l in HOST_MKL_LIBRARIES.split()])}}` in the yaml files.

For a while ago, I successfully built the FEniCS stack with the Intel compilers and MKL on our local CentOS cluster. It is not based on the new parameter system, but you can [take a look](https://github.com/hashdist/hashstack/compare/johannr/mkl-abel) if you are interested.

**Comment by davydden** [comment]
thanks for the link, nice to see that not only you used `mkl` but also intel compilers. I will try adopting it to my needs to build `petsc`, `trilinos`, `deal.ii`.

Things like `{{' '.join(['-l' + l for l in HOST_MKL_LIBRARIES.split()])}}` will be handy to feed MKL libraries to different packages. Well, one can only hope that this parameter system will be in action soon ;-)

**Comment by davydden** [comment]
@johannesring I almost made it work, have some minor issues compiling my code against the stack. Thus i was curious why do you have `Note: make sure to load the gcc/4.9.2 module before building this profile` line? `gcc` is already loaded in `prologue`, it's prologue executed for every build?

**Comment by ahmadia** [comment]
> isn't prologue executed for every build

Yes it is.

**Comment by johannesring** [comment]
I had to load the `gcc` module before running `hit build` or otherwise I got errors during `hit build-postprocess`, like this for `bzip2`:
``` console
...
[bzip2] running ['hit', 'build-postprocess', u'--shebang=multiline', u'--write-protect', u'--relative-sh-script=/bin/.*-config', u'--relative-pkgconfig', u'--relative-rpath', u'--relative-symlinks', u'--relative-symlinks', u'--check-relocatable', u'--check-ignore=.*\\.pyc$', u'--check-ignore=.*\\.pyo$']
[ERROR] [u'/cluster/home/johannr/.hashdist/bld/patchelf/47vdsd2t5ish/bin/patchelf', '--shrink-rpath', u'/cluster/home/johannr/.hashdist/bld/bzip2/uvcqyurczi5p/bin/bzip2'] failed: 1
[bzip2|ERROR] hit command failed: Command [u'/cluster/home/johannr/.hashdist/bld/patchelf/47vdsd2t5ish/bin/patchelf', '--shrink-rpath', u'/cluster/home/johannr/.hashdist/bld/bzip2/uvcqyurczi5p/bin/bzip2'] failed with code 1 and stderr:
/cluster/home/johannr/.hashdist/bld/patchelf/47vdsd2t5ish/bin/patchelf: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /cluster/home/johannr/.hashdist/bld/patchelf/47vdsd2t5ish/bin/patchelf)
```
I didn't report it because I wasn't sure if it was a bug in HashDist...

**Comment by davydden** [comment]
wow, interesting. That may explain some issues i had when trying to use the stack. I have not had errors building it, though. But I was also building it in several stages, so I am not sure if I had `gcc` loaded for some or not.

**Comment by ahmadia** [comment]
> I didn't report it because I wasn't sure if it was a bug in HashDist...

Yeah, interesting.  This is *definitely* a bug in HashDist since we assume that post-processing can safely be done from the "master" environment as opposed to the build environment the user is in, but this is clearly not true from your report above.  This has interesting upstream implications.  cc @dagss @certik @cekees and yes, follow @johannesring 's advice for now.

**Comment by cekees** [comment]
Is the issue that the  patchelf build being used is missing the proper rpath options or something to ensure it is independent of the LD_LIBRARY_PATH? Could we statically link patchelf and any other tools hashdist builds itself  to  use  in post-processing? It seem like in general it's not hashdist's responsibility to ensure that pacakges are built in a way that  makes  them independent of their environment.

**Comment by ahmadia** [comment]
> Is the issue that the patchelf build being used is missing the proper rpath options or something to ensure it is independent of the LD_LIBRARY_PATH?

It looks like we're not running prologue before we execute the patchelf post-process step because the post-process step isn't part of the "build".  We had a discussion about whether post-process was part of the build or part of `hit` the utility.  I think this is a point in favor of treating (at least this step) as part of the build/hashstack instead of part of hashdist.
