### ISSUE TITLE
Downloading OpenSSL fails

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#893]
Version 1.0.2e of OpenSSL was released yesterday and the old version (1.0.2d) was [moved](http://www.openssl.org/source/old/1.0.2/openssl-1.0.2d.tar.gz). Now I get this:

``` console
Downloading http://www.openssl.org/source/openssl-1.0.2d.tar.gz...
[ERROR] urllib failed to download (code: 404): http://www.openssl.org/source/openssl-1.0.2d.tar.gz
```
Since they are moving the old tarball when making a new release, it is probably better to use [GitHub](https://github.com/openssl/openssl/releases) as the default download location.

**Comment by vbraun** [comment]
See #895
