### ISSUE TITLE
VTK library and python

### ISSUE THREAD

**Issue by balborian** [hashdist/hashstack#983]
I've tried these options to install VTK with hashdist (on OSX, I extend the osx.yaml):

```
vtk:
```
```
vtk:
    vtk_wrap_python: true
```
```
vtk:
    vtk_wrap_python: false
```
but in all cases the vtk-python libraries are linked to the wrong libraries:
```
salazardetro1@frankenstein:~/.hashdist/bld/vtk/vyl5qs6ziice/lib/python2.7/site-packages/vtk$ otool -L vtkCommonPython.so 
vtkCommonPython.so:
	/Users/salazardetro1/.hashdist/tmp/vtk-vyl5qs6ziice/_build/bin/libvtkCommonPythonD.5.10.dylib (compatibility version 5.10.0, current version 5.10.1)
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
	/Users/salazardetro1/.hashdist/tmp/vtk-vyl5qs6ziice/_build/bin/libvtkPythonCore.5.10.dylib (compatibility version 5.10.0, current version 5.10.1)
	/Users/salazardetro1/.hashdist/tmp/vtk-vyl5qs6ziice/_build/bin/libvtkCommon.5.10.dylib (compatibility version 5.10.0, current version 5.10.1)
	/Users/salazardetro1/.hashdist/tmp/vtk-vyl5qs6ziice/_build/bin/libvtksys.5.10.dylib (compatibility version 5.10.0, current version 5.10.1)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```
The directory `~/.hashdist/tmp/vtk-vyl5qs6ziice/` is deleted when the installation is complete. It should be pointing to `~/.hashdist/bld/vtk/vyl5qs6ziice/` instead. How can I fix this? Thanks.

Is it related to the [these lines](https://github.com/hashdist/hashstack/blob/b7ec4261f16ec64a10718d73c27f722e42749d43/pkgs/vtk/vtk.yaml#L86) not being executed?

**Comment by cekees** [comment]
I haven't worked on vtk within hashdist, but I'm guessing you're going to have to modify the -D options in vtk.yaml unitl  you force cmake to link properly to the proper paths.

**Comment by balborian** [comment]
So is this the line to blame (https://github.com/hashdist/hashstack/blob/master/pkgs/vtk/vtk.yaml#L63) ? ${ARTIFACT} is the tmp directory right?

**Comment by cekees** [comment]
No, ${ARTIFACT} is the permanent thing in bld/vtk/..., so that is correct.

**Comment by johannesring** [comment]
I fixed a similar issue in the FEniCS fork of HashStack a few days ago. First I solved it with some rpath tricks ([here](https://github.com/FEniCS/hashstack/commit/6a83aef87f6c529838c2429a18f2e987a642fc1a)), but then I found that setting `CMAKE_MACOSX_RPATH=ON` also fixed the problem ([here](https://github.com/FEniCS/hashstack/commit/05075f4ed1d639ba75702386e571ab536a4e3c49) and [here](https://github.com/FEniCS/hashstack/commit/3ff6a9ede560aa93d38ae2d349360a118eece0fc)).

Note that it is VTK 7 in the fork.

**Comment by balborian** [comment]
Now it's working with the FEniCS fork. Thanks!
